version: '3'

services:
  db:
    image: 'mysql:5.7'
    volumes:
      - 'mysql:/var/lib/mysql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  api:
    depends_on:
      - db
      - redis
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'

volumes:
  redis:
  postgres: