default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("DB_DEVELOPMENT_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("DB_DEVELOPMENT_HOST") { 'localhost' } %>

development:
  <<: *default
  database: demo_project_develop

test:
  <<: *default
  database: demo_project_test

production:
  <<: *default
